### ISSUE TITLE
Some fields are unsearchable

### ISSUE THREAD

**Issue by ghost** [piplcom/piplapis-python#11]
person = Person()
person.names.append(Name(first='Thalia'))
request = SearchAPIRequest(api_key='SECRET', person=person)
response = request.send()
File "", line 1, in 
File "/root/PythonProjects/venv/lib/python3.5/site-packages/piplapis/search.py", line 315, in send
self.validate_query_params(strict=strict_validation)
File "/root/PythonProjects/venv/lib/python3.5/site-packages/piplapis/search.py", line 255, in validate_query_params
raise ValueError('Some fields are unsearchable: %s' % self.person.unsearchable_fields)
ValueError: Some fields are unsearchable: [Name(first='Thalia')]

**Comment by roy-pipl** [comment]
Hi, this is not an issue. A full name must be supplied with a first name and last name with 2 or more characters at minimum.
See https://docs.pipl.com/v5.0/reference#overview-1
https://docs.pipl.com/v5.0/reference#using-search-parameters
