### ISSUE TITLE
New version with support for 3.4+

### ISSUE THREAD

**Issue by srabi** [piplcom/piplapis-python#2]
Hi guys,
I would be great if you can port the code to python 3.4 and above.
Thanks.

**Comment by waqaraqeel** [comment]
@srabi Hope you will find this helpful:
https://github.com/waqaraqeel/piplapis-python3
https://pypi.python.org/pypi/piplapis-python3/5.1

**Comment by joshliberty** [comment]
@srabi, as of version 5.0.8, the library supports python 3 (all minor versions).
@waqaraqeel - I hope this addresses your need too, thank you for your contribution!
