### ISSUE TITLE
cannot set MITM certificate for forward proxy

### ISSUE THREAD

**Issue by guzzijones** [piplcom/piplapis-python#27]
the send function does not allow for us to set our MITM proxy certificate bundle file.

https://github.com/piplcom/piplapis-python/blob/f43c956f5cb80085cb00c731939d8c6ea22da8c0/piplapis/search.py#L343

**Comment by roy-pipl** [comment]
Hi @guzzijones. Thank you for your feedback. Please would you kindly reach out to us with the name of the organization you are integrating to Pipl with, we would love to assist you with your Pipl API integration. https://pipl.com/customer-support

Also in the meantime, may I suggest investigating a workaround: https://stackoverflow.com/questions/1450132/proxy-with-urllib2
