### ISSUE TITLE
user_id not a valid paramter for SearchAPIRequest

### ISSUE THREAD

**Issue by mikec83** [piplcom/piplapis-python#9]
I would assume that the list of parameters here (https://pipl.com/dev/reference/?python#using-search-parameters) would all be valid key word arguments to the SearchAPIRequest.  However, user_id is not supported, nor is zip code or phone.

It should be noted that using a manual PIPL api URL such as api.pipl.com/search?user_id=abcd@facebook works in a web browser, so user_id should be an allowable kwarg for the SearchAPIRequest, no?

**Comment by joshliberty** [comment]
Hi Mike,

I'll add user_id as a parameter to the SearchAPIRequest constructor. In the meantime, please note that you can still send a user_id, by creating a UserID object, and attaching it to the Person object at SearchAPIRequest.person.

Josh

**Comment by glerinsonum** [comment]
@caligula1989 Hello. How many "error": "The query does not contain any valid name/username/user_id/phone/email/address to search by" 

How many querys queries have pipl, like objectives. 
And. Learn us. How can put in work this script pipl from python.

**Comment by yuri1992** [comment]
It has been fixed in 5.2.0v
